# Generated by Django 4.2.3 on 2023-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productslist',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
